### ISSUE TITLE
Won't Compile Under Access 12064.20466

### ISSUE THREAD

**Issue by grahampcharles** [francescofoti/Reading_Text_Files#1]
Your Reading_Text_Files.accdb won't compile under the current Access -- you get a Type Mismatch on VarPtr in UTF8DecodeByteArrayToString , since in #Win64 VarPtr returns a LongPtr instead of a Long.

**Comment by francescofoti** [comment]
Right. I didn't finish the job for the Win64 version at that time, will post an update with the necessary changes I got. Thanks Charles.

**Comment by francescofoti** [comment]
Just pushed an update which should make it work in 64bits VBA, MD5() was causing crashes also, so changed it also.
